### ISSUE TITLE
Unable to register & no apparent error dialog

### ISSUE THREAD

**Issue by Wilker-a** [syphon-org/syphon#136]
username OK, password with minor struggles (), captha done with some struggle (see #135), but on the screen to accept terms of service, clicking "Finish" gives a Loading animation, but then it stops loading something but nothing changes — i can click "Finish" again for the same effect, checkbox can be toggled still, and the rest of the screen remains unchanged.

###### v0.0.16 as of now, under Android 5.1.1

**Comment by ereio** [comment]
This also should have been fixed since v0.0.16 (the current version is v0.0.19 at the time of this issue) but I think was reintroduced after the Riot rebrand / recent matrix.org changes since signup is no longer working again. Will fix in this weekends release.

Thanks for opening issues and testing it out! I appreciate it.

**Comment by ereio** [comment]
Note: It's email identity, matrix.org started requiring it during signup last week

**Comment by Wilker-a** [comment]
btw i haven't checked yet: are exceptions sent to debug logs so programs such as Matlog and Logcat can view it? it would be useful to have an easy way to see and copy Exceptions for reporting errors :3

**Comment by ereio** [comment]
Unless the app hard crashes, logs likely won't be printed out. That's just to make sure data doesn't get leaked from logs on accident.

However, I've added global error snackbars for expected exceptions, so you should hopefully see something now :)

**Comment by Wilker-a** [comment]
thank you :heart:
