### ISSUE TITLE
Render Edited Messages

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#197]

**Comment by ereio** [comment]
This involves mutating the state of the messages locally after parsing through them, but before presenting them to the user. I'm putting this off because that can get ugly fast if done incorrectly. I'm prioritizing stability and features needed to verify sessions for e2ee (key import/exports and cross signing)

Shouldn't be too long from now though, just maybe around 0.1.6 or 0.1.7. I'll use this issue to track implementing message editing 👍.
