### ISSUE TITLE
Filter Unpermitted Message Edits

### ISSUE THREAD

**Issue by ereio** [syphon-org/syphon#242]
While Syphon doesn't currently allow editing messages in app, edits made by a different user to your message in other clients are still rendered as valid in Syphon. Anyone's message edit to _anyone else's_ message will appear valid. 

This appears possible due to the homeserver sometimes allowing all json payloads for sendable messages whether they are technically valid or not

**Comment by TR-SLimey** [comment]
The issue has now been fixed in Element Android (https://github.com/vector-im/element-android/pull/2940 commits [bdec23f](https://github.com/vector-im/element-android/pull/2940/commits/bdec23f740608915538b0d164b05f86926918d2c) and [c33af6d](https://github.com/vector-im/element-android/pull/2940/commits/c33af6de6a9f1adda23cfbf33cadc177a96d0265)) so I can provide a proof of concept and some more details.

The PoC I originally provided to Element was the following event sent from Element Web's devtools in an **unencrypted** room (the bug should work in encrypted rooms also, but requires a modified client):

```
{
        "m.new_content": {
            "msgtype": "m.text",
            "body": "EDITED BY ANOTHER ACCOUNT"
        },
        "m.relates_to": {
            "rel_type": "m.replace",
            "event_id": "$<ID_OF_ORIGINAL_MESSAGE>"
        },
        "msgtype": "m.text",
        "body": " * EDITED BY ANOTHER ACCOUNT"
}
```
The above should be sent from one account and reference the ID of a message by another. The edit will not be rendered at all by Element Web and also Element Android post-1.1.1, but will be rendered as a valid edit by Syphon.

Something alike to Element's fix in the commits above should probably be implemented to prevent this.

I also asked Element's security team about whether this is a client responsibility or a server responsibility and they said that it is a client responsibility as to allow for possibly encrypting event relationships in the future, although server-based mitigation could be applied also, but this is only an additional measure.

I also have the PoC video I originally provided to Element. It uses Element Android for the demo, but the same thing applies to Syphon. That can be found here: https://files.0x1a8510f2.space/s/MjFP2wNPanjfDnB

**Comment by ereio** [comment]
@TR-SLimey will try to get a merge to fix this by EOD tomorrow

**Comment by TR-SLimey** [comment]
Awesome! Good to see you back btw :D

**Comment by ereio** [comment]
I got a job!

**Comment by TR-SLimey** [comment]
Ooh yea! Really glad to hear that! You should announce it in the Syphon channel :D 🥳🎉🎉

**Comment by ereio** [comment]
Lol was just going to tell you I got a job in the channel, but it's fine here too :)

**Comment by TR-SLimey** [comment]
This issue is gonna be fun to read later with the orphaned comments xD but yes, why not both after all? This kind of news is worth reading twice :P
