### ISSUE TITLE
App not decrypting new messages

### ISSUE THREAD

**Issue by eldondev** [syphon-org/syphon#319]
I installed the app about two weeks ago, and it was working fine. Messages received this week do not seem to be decryptable. I can still see the receipt of new messages from the user, and send new messages, but the new ones coming in aren't decrypted. I can ask if they can still decrypt mine.

**Comment by eldondev** [comment]
Anything I can do to help with this? Looks like they also cannot decrypt my messages. I looked at the encrypted session content, it looks like syphon puts it all in a flutter encrypted store. Not super familiar with flutter or olm/megaolm. I see you've gotten session key import/export to work, would that help with this? thanks! I know you've put a lot of work into this.

**Comment by ereio** [comment]
Thanks for bringing this to my attention and for the kind words! :) 

Just to be clear, is the encrypted chat / room in question one you created after authenticating a session in Syphon or was it a previously existing chat?

Syphon's encryption currently only works for new chats created after creating a session in the app. You're right in that key imports would work for helping decrypt existing chats. I had intentionally left out key import / exports until the app could be deemed more stable (or move to beta) but it's come a good ways since then and many people want to try. I hope to enable key imports / exports in the next release with a warning that the app is still in Alpha.

If the chat was a new chat and is no longer encrypting / decrypting messages, that's certainly a bug. The key import / export potentially wouldn't help with the issue and there's something else going on.

If this is the case, I'll try to see if I can recreate the issue over time. I had assumed this was the issue and was going to attempt it this weekend. Syphon currently doesn't recover from corrupted Olm / Megolm sessions which is a feature that several clients have behind the scenes. That's also pretty high on the priority list!

Let me know if I've understood the issue right and I'll try to deploy a fix this weekend! :)

**Comment by eldondev** [comment]
You've got it right. I brought up a new matrix home server to federate with the matrix homeserver of a friend. I created the account via syphon, and up until last night when I connected gomuk, I had only used syphon to log into it.

**Comment by milada-horakova** [comment]
tried to create the conversation from both sides. sometimes the element user can decrypt the message in other cases there is a 'sender did not send key' error. messages from element user to syphon couldn't be decrypted at all. both users are on different home servers.

![IMG_20210806_182622](https://user-images.githubusercontent.com/28026033/128689206-ae598657-a6cd-4deb-9db2-5656fadedc83.jpg)

device: blackphone bp1, android 4.4.4
tested with 0.1.9 and 0.1.10 via f-droid

**Comment by ereio** [comment]
@milada-horakova thanks for testing this extensively!

Outside Olm/Megolm recovery I've mentioned here previously, I found a few issues when testing over the weekend. Syphon is not replaying decryption when it should and creating new Olm sessions with previously messaged sessions or users is being blocked by Syphon. 

Working on fixes now that should hopefully be ready / deployed this upcoming weekend (Aug. 14th)

**Comment by milada-horakova** [comment]
this is what i get on 0.1.13 currently. syphon now also doesn't show the sent messages.
![IMG_20210929_170925](https://user-images.githubusercontent.com/28026033/135300268-44138fe8-0e2c-432e-8325-5cf7f4c9d1fd.jpg)
![IMG_20210929_170942](https://user-images.githubusercontent.com/28026033/135300303-bd6bd5aa-ec90-4c8c-b468-432d07ad4189.jpg)
