### ISSUE TITLE
decide weather to call rooms 'rooms' or 'chats'

### ISSUE THREAD

**Issue by valentinleistner** [syphon-org/syphon#347]
Currently rooms are sometimes called 'rooms' and sometimes 'chats' which can sometimes be confusing. In the GUI it is mostly 'chat' (e. g. Settings/Chats, 'Toggle Direct Chat', 'Leave Chat', ...) whereas in the code it is mostly 'room' (e. g. class 'Room', 'room.dart', directory 'rooms', ...). A uniform convention would be appreciated.

**Comment by ereio** [comment]
All the In-App Copy should now always refer to rooms as "Chats" (was not the case in previous builds by accident)

The View layer itself should always refer to them as "Chats", as it's only a distinction made by the GUI of Syphon

The Domain (State) & View Model logic should always refer to them as "Rooms"

For clarity:

Domain / State Logic (Rooms)  -> View Model (Rooms) -> View (Chats) -> Copy (Chats)

If you notice there's a piece of a layer above that's misnamed, feel free to change it. Otherwise, the distinction is purposeful since we're ultimately tied to the way that Matrix works and their naming conventions. 

Happy to discuss alternatives and / or the separations here, just wanted to clarify the currently desired structure.
