### ISSUE TITLE
Incomplete room member list preview

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#438]
Group room member list overview in room settings screen is incomplete. When the complete user list is opened, the overview is loaded correctly too. Maybe refresh user list when opening room settings?

1. open room settings screen from top bar
2. member overview is incomplete
3. open "all chat users" -> member list reloaded
4. go back
5. overview is complete

Tested on v0.2.3

**Comment by ereio** [comment]
Thought I fixed this, will confirm the fix made it in

**Comment by ereio** [comment]
Without pulling every user upon opening the settings page, we only have the following information:
- the number of users in the room
- the profile information of the users corresponding to the most recent messages

To reduce the amount of data loaded, I'm intentionally not loading everyone's profile information in the room unless you choose to see all users (unfortunately the spec is somewhat all or nothing). Otherwise, I only show the most recent users in the messages loaded to compensate. To make this clearer, I've added the "more" icon to always show alongside the user "preview" if we know the users we've pulled locally is less than the `totalJoinedUsers` amount.
