### ISSUE TITLE
Deleting a device throws error

### ISSUE THREAD

**Issue by EdGeraghty** [syphon-org/syphon#571]
![image](https://user-images.githubusercontent.com/20861699/154303679-36eab386-568b-4762-85d3-9e5c877eb65f.png)
![image](https://user-images.githubusercontent.com/20861699/154303896-ac62dcfe-4d06-4bd7-98f4-7cdebc689ce4.png)

**Comment by ereio** [comment]
This was the same issue as the captcha back in 0.2.6. Has to do with a recent change to Flutter that doesn't scope the redux store inside a dialog view for the password check dialog here. If that's enough to go on for you (should be the same thing as the signup captcha issue) feel free to check it out! Otherwise, I'll push a fix before 0.2.9

**Comment by ereio** [comment]
fixed with https://github.com/syphon-org/syphon/commit/80a6114988076b3404a8756b11bd5e3297dabd0c
