### ISSUE TITLE
What happened to gitea releases?

### ISSUE THREAD

**Issue by Mederim** [syphon-org/syphon#773]
I wan't to get the nightly builds and when i click the link in the readme it gives me nothing and not load the gitea repo

**Comment by ereio** [comment]
they should be coming back soon, the old way we handled gitea releases no longer works with the latest gitea release :( so we need to rework our workflow

**Comment by Mederim** [comment]
Theres some other way to get nightly builds?

**Comment by 0x1a8510f2** [comment]
If you are able to build from source using the instructions in the readme, that will probably be the quickest. Otherwise, there isn't really any other source of nightlies. I used to have some unofficial nightlies but that infrastructure is long gone.

If you tell me what device you have, or just what cpu arch/OS it's using, I might be able to make a build for you if gitea takes too long and I have a minute.

**Comment by xusiai** [comment]
Are Gitea release still planned for a comeback?
