### ISSUE TITLE
Enable additional flutter_lints rules

### ISSUE THREAD

**Issue by AdiAr11** [syphon-org/syphon#774]
I saw in analysis_options.yaml file that most of the rules are set to false. Also there are some rules missing like prefer_const_declarations. Enabling these will have a good impact. 
prefer_const_declarations will identify widgets that are constant and will highly improve performance.

**Comment by AdiAr11** [comment]
@ereio I can start working on this as well if confirmed!

**Comment by ereio** [comment]
Flutter linting should already occur under the `dev` branch as seen here when I was cleaning things up with `dart fix`

https://github.com/syphon-org/syphon/commit/2c1d29416c517b92b63c561ba6e9b843f371e0d1

Just want to make sure there isn't more clarity needed around using flutter_lint in the repo. Working on enabling some of the disabled lint rules sounds good otherwise!

**Comment by AdiAr11** [comment]
Yes a few rules have been set to false in analysis_options.yaml file, which could improve performance. will create a pr, if it's not right or require changes, please let me know

**Comment by ereio** [comment]
Sounds good to me!
